"""Fix created_by column

Revision ID: 189dc463a3f6
Revises: 
Create Date: 2025-09-12 11:21:06.349296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189dc463a3f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
